---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see <https://www.gnu.org/licenses/>.

##
# Deploy the Moodle source code.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Ensure Git source code management system is available
  become: yes
  ansible.builtin.apt:
    package: git
    state: present

- name: Ensure existence and accessibility of parent of deployment directory
  become: yes
  ansible.builtin.file:
    path: "{{ moodle_deploy_destination | dirname }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx

- name: Deploy Moodle source code
  ansible.builtin.git:
    repo: "{{ moodle_deploy_repository }}"
    version: "{{ moodle_deploy_version }}"
    update: "{{ moodle_deploy_update }}"
    dest: "{{ moodle_deploy_destination }}"