---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see <https://www.gnu.org/licenses/>.

##
# Install the specified database service and create the required database with
# associated user.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Database Service - PostgreSQL
  # See https://www.postgresql.org/docs/14/app-initdb.html
  when: moodle_cfg_dbtype == 'pgsql'
  vars:
    moodle_postgresql_version: 14
    moodle_postgresql_bin: /usr/lib/postgresql/{{ moodle_postgresql_version }}/bin
    moodle_postgresql_lib: /var/lib/postgresql/{{ moodle_postgresql_version }}/main
  block:
    - name: Download signing key for PostgreSQL APT package repository
      become: yes
      ansible.builtin.uri:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        status_code:
          - 200
          - 304
        dest: /etc/apt/keyrings/postgresql.asc
        creates: /etc/apt/keyrings/postgresql.asc

    - name: Add APT package repository for PostgreSQL
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present

    - name: Install PostgreSQL
      become: yes
      ansible.builtin.apt:
        package:
          - postgresql-{{ moodle_postgresql_version }}
          - postgresql-contrib-{{ moodle_postgresql_version }}
          - libpq-dev        # Necessary for postgresql_* modules
          - python3-psycopg2 # Necessary for postgresql_* modules
          - acl              # Necessary for initializing PostgreSQL
          - php{{ php_version }}-pgsql
        state: present

    - name: Status of PostgreSQL access configuration file
      become: yes
      ansible.builtin.stat:
        path: "{{ moodle_postgresql_lib }}/pg_hba.conf"
      register: moodle_postgresql_pg_hba_conf_file

    - name: Ensure PostgreSQL data directory is empty if PostgreSQL has not been initialized
      when: not moodle_postgresql_pg_hba_conf_file.stat.exists
      become: yes
      ansible.builtin.file:
        path: "{{ moodle_postgresql_lib }}"
        state: absent

    - name: Initialize PostgreSQL
      when: not moodle_postgresql_pg_hba_conf_file.stat.exists
      become: yes
      become_user: postgres
      ansible.builtin.command:
        cmd: "{{ moodle_postgresql_bin }}/initdb --pgdata={{ moodle_postgresql_lib }} --auth-host=md5 --auth-local=peer"
        creates: "{{ moodle_postgresql_lib }}/pg_hba.conf"

    - name: Start PostgreSQL service
      become: yes
      ansible.builtin.sysvinit:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database user
      become: yes
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ moodle_cfg_dbuser }}"
        password: "{{ moodle_cfg_dbpass }}"
        state: present

    - name: Create database
      become: yes
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ moodle_cfg_dbname }}"
        state: present
        owner: "{{ moodle_cfg_dbuser }}"

- name: Database Service - MariaDB
  # See https://mariadb.org/download/?t=repo-config&d=20.04+%22focal%22&v=10.6&r_m=liquidtelecom
  when: moodle_cfg_dbtype == 'mariadb'
  vars:
    moodle_mariadb_version: 10.6
  block:
    - name: Ensure APT keyrings directory exists
      # The /etc/apt/keyrings directory does not exist on Ubuntu 20.04
      become: yes
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Download signing key for MariaDB APT package repository
      become: yes
      ansible.builtin.uri:
        url: https://mariadb.org/mariadb_release_signing_key.pgp
        status_code:
          - 200
          - 304
        dest: /etc/apt/keyrings/mariadb-keyring.pgp
        creates: /etc/apt/keyrings/mariadb-keyring.pgp

    - name: Add APT package repository for MariaDB
      become: yes
      ansible.builtin.apt_repository:
        repo:  deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://mariadb.mirror.liquidtelecom.com/repo/{{ moodle_mariadb_version }}/ubuntu {{ ansible_distribution_release }} main
        state: present

    - name: Install MariaDB
      become: yes
      ansible.builtin.apt:
        package:
          - mariadb-server
          - python3-pymysql # Needed for mysql_* modules
          - php{{ php_version }}-mysql
        state: present

    - name: Start MariaDB service
      become: yes
      ansible.builtin.sysvinit:
        name: mariadb
        state: started
        enabled: yes

    - name: Create database
      become: yes
      community.mysql.mysql_db:
        login_unix_socket: /run/mysqld/mysqld.sock
        name: "{{ moodle_cfg_dbname }}"
        state: present

    - name: Create database user
      become: yes
      community.mysql.mysql_user:
        login_unix_socket: /run/mysqld/mysqld.sock
        name: "{{ moodle_cfg_dbuser }}"
        password: "{{ moodle_cfg_dbpass }}"
        priv: "{{ moodle_cfg_dbname }}.*:ALL"
        state: present
