---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see
# <https://www.gnu.org/licenses/>.

##
# Sets the default values of the role's variables that can be overridden.
#
# @copyright  2023 Geoffrey Bernardo van Wyk {@link https://geoffreyvanwyk.dev}
# @link       http://tinyurl.com/ansible-variable-precedence
##

# ------ Basic {{{1

moodle_version: "4.3"

# Whether the Moodle instance is installed for 'development', or 'production'.
# In a development environment, certain things can be allowed, e.g. Moodle
# development mode, unstable plugins, Xdebug etc.
moodle_environment: production

# ------ Deployment of Source Code {{{1

# Public repository.
moodle_deploy_repository: https://github.com/moodle/moodle

# Branch, tag, or commit.
moodle_deploy_version: "{{
  lookup('geoffreyvanwyk.moodle.stable_branch', moodle_version=moodle_version)
  }}"

# Whether to pull new commits.
moodle_deploy_update: true

# This should be the document root or subdirectory of the document root of a
# web service virtualhost.
moodle_deploy_destination: /var/www/html/moodle

# ------ Set-Up of Database {{{1

# Whether or not to install a database service.
moodle_db_install: true

# Which database service to use: PostgreSQL (pgsql) or MariaDB (maridb).
moodle_db_type: pgsql

## The name of the database.
moodle_db_name: moodle

# If a database service has to be installed, this user will be created with
# administrative provileges on the database.
moodle_db_username: moodler

# Random string generated for database password.
moodle_db_password: "{{
  lookup('ansible.builtin.password',
  '/tmp/' + moodle_db_username + '-db_password',
  length=24,
  chars=['ascii_letters', 'digits'])
  }}"

# ------ Web Hosting {{{1

# Whether to serve Moodle with Apache httpd (apache2) or Nginx (nginx).
moodle_web_service: apache2

# Whether Moodle is served over 'https' or just 'http'.
moodle_web_protocol: http

# Domain name of the web service virtual host.
moodle_web_domain: 127.0.0.1

# Subdirectory path relative to the document root of the web service virtual
# host, without leading or trailing slashes.
# It must not include any spaces anywhere.
moodle_web_path: moodle

# Whether to serve Moodle from a subdirectory or virtualhost.
#
# When served from a subdirectory, variables:
#
# - moodle_deploy_destination: must be a subdirectory of the document root of
#                              an existing virtual host.
# - moodle_web_path:           must be subdirectory path relative to the
#                              document root of the existing virtual host and
#                              it must match moodle_deploy_destination.
moodle_web_root: subdirectory

# Directories in the Moodle source code that must NOT be directly accessible
# over the web and for which the web server must respond with Not Found.
#
# The list of directories to be protected can be found on an existing Moodle
# instance (e.g. sandbox.moodledemo.net) by visiting:
# "Site Administration > Reports
#                      > Security Checks
#                      > Check public/private paths".
moodle_web_protected_directories:
  - \.git
  - \.github
  - \.idea
  - \.vscode
  - behat
  - lib/classes
  - fixtures
  - node_modules
  - vendor

# Files in the Moodle source code that must NOT be directly accessible
# over the web and for which the web server must respond with Not Found.
#
# The list of files to be protected can be found on an existing Moodle
# instance (e.g. sandbox.moodledemo.net) by visiting:
# "Site Administration > Reports
#                      > Security Checks
#                      > Check public/private paths".
moodle_web_protected_files:
  - \.env
  - \.lock
  - \.stylelintrc
  - behat\.yml\.dist
  - behat\.yml
  - composer\.json
  - composer\.lock
  - db/install\.xml
  - environment\.xml
  - package\.json
  - package\.lock
  - phpunit\.xml
  - phpunit\.xml\.dist
  - readme\.txt
  - readme_moodle\.txt
  - README\.txt
  - README\.md
  - upgrade\.txt

# ------ Install & Server-side Configuration {{{1

# Database connection details.
moodle_cfg_dbtype: "{{ moodle_db_type }}"
moodle_cfg_dbname: "{{ moodle_db_name }}"
moodle_cfg_dbuser: "{{ moodle_db_username }}"
moodle_cfg_dbpass: "{{ moodle_db_password }}"

# File system permissions that must be applied to new directories created
# within the moodledata directorry.
moodle_cfg_directorypermissions: "02777"

# Name and description of the Moodle instance.
moodle_site_fullname: Modular Object-Oriented Dynamic Learning Environment
moodle_site_shortname: Moodle
moodle_site_summary: >-
  Moodle is the world’s most customisable and trusted eLearning solution that
  empowers educators to improve our world.

# Site administrator credentials.
moodle_admin_username: moodler
moodle_admin_password: N3verstople@rning
moodle_admin_email: moodler@never.stops.learning
moodle_support_email: "{{ moodle_admin_email }}"

# A dictionary of settings placed in config.php so that the site administrator
# cannot change them, e.g.
#
# moodle_cfg_forcedsettings:
#   additionalhtmlfooter: '<style>p {color: red}</style>'
#   enabledashboard: 0
#   navcourselimit: 12
moodle_cfg_forcedsettings: {}

# ------ Extend with Plugins {{{1

# Download plugins from a Git repository in case they are not in the Moodle
# plugins directory. For example:
#
# moodle_plugins_git;
#   - name: block_todos
#     repository: https://github.com/example/moodle-block_todos
#     version: master
#   - name: theme_learningsandboxonline
#     repository: >-
#       https://github.com/geoffreyvanwyk/moodle-theme_learningsandboxonline
#     version: MOODLE_403_STABLE
moodle_plugins_git: []
