---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see
# <https://www.gnu.org/licenses/>.

##
# Continuous integration in GitHub Actions that lints the Ansible code and tests
# the role with Molecule.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
# @see        GitHub Actions {@link https://docs.github.com/en/actions}
##

name: Build
"on":
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: "geoffreyvanwyk.moodle"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "geoffreyvanwyk.moodle"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        molecule-scenario:
          - default
          - config_settings
          - mariadb
          - plugins
        ubuntu-version:
          - ubuntu2004
          - ubuntu2204
        moodle-version:
          - 4.1
          - 4.2
          - 4.3

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "geoffreyvanwyk.moodle"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test --scenario-name ${{ matrix.molecule-scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.ubuntu-version }}
          MOLECULE_MOODLE_VERSION: ${{ matrix.moodle-version }}
