---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see <https://www.gnu.org/licenses/>.

##
# Publishes a new version (as specified with a Git tag) of the role to Ansible
# galaxy.
#
# It requires a GALAXY_API_KEY secret present in the GitHub repository or
# organizaton settings. The API key can be obtained from the Preferences page of
# your Ansible Galaxy profile.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
# @see        GitHub Actions {@link https://docs.github.com/en/actions}
# @see        {@link https://github.com/marketplace/actions/publish-ansible-role-to-galaxy}
# @see        {@link https://github.com/ansible/galaxy/issues/46}
##

name: Publish
"on":
  push:
    tags:
      - "v*"

defaults:
  run:
    working-directory: "geoffreyvanwyk.moodle"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "geoffreyvanwyk.moodle"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          touch ansible.cfg
          &&
          ansible-galaxy role import -vvv --api-key ${{ secrets.GALAXY_API_KEY }} --role-name moodle
          geoffreyvanwyk https://github.com/geoffreyvanwyk/ansible-role-moodle
